# Generated by Django 4.2.4 on 2023-11-07 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_categoria_p_delete_categoria_pm"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="categoria_p",
            new_name="categoria_pm",
        ),
        migrations.AlterModelTable(
            name="categoria_pm",
            table="categoria_pm",
        ),
    ]
