# Generated by Django 4.2.4 on 2023-11-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_categoria_pm_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="producto_pm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("descripcion", models.TextField(max_length=100)),
                ("precio", models.IntegerField(max_length=20)),
                ("img", models.ImageField(blank=True, upload_to="productos/")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.categoria_pm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "producto_pm",
            },
        ),
    ]
