# Generated by Django 4.2.4 on 2023-11-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_producto_pm_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto_pm",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
