# Generated by Django 4.2.4 on 2023-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_producto_pm_precio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("productos", models.ManyToManyField(to="main.producto_pm")),
            ],
            options={
                "db_table": "Carrito",
            },
        ),
    ]
