# Generated by Django 4.2.4 on 2023-11-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_carrito_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProCarrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.carrito"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.producto_pm",
                    ),
                ),
            ],
            options={
                "db_table": "ProCarrtio",
            },
        ),
    ]
