# Generated by Django 4.2.4 on 2023-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_procarrito"),
    ]

    operations = [
        migrations.CreateModel(
            name="cupones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("fecha_i", models.DateField(blank=True, null=True)),
                ("fecha_f", models.DateField(blank=True, null=True)),
                ("limite", models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "cupones",
            },
        ),
    ]
