# Generated by Django 4.2.4 on 2023-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_cupones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupones",
            name="limite",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
