# Generated by Django 4.2.4 on 2023-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_cupones_limite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupones",
            name="descuento",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
