# Generated by Django 4.2.4 on 2023-11-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_cupones_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupones",
            name="usado",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
