# Generated by Django 4.2.4 on 2023-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_recets"),
    ]

    operations = [
        migrations.AddField(
            model_name="recets",
            name="tipo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
