# Generated by Django 4.2.4 on 2023-11-20 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_recets_tipo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recets",
            old_name="video",
            new_name="videoo",
        ),
    ]
