# Generated by Django 4.2.4 on 2023-11-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_bitacors_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitacors",
            name="fecha",
            field=models.DateTimeField(),
        ),
    ]
