# Generated by Django 4.2.4 on 2023-11-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0021_alter_bitacors_fecha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LIKE", "Like"),
                            ("DISLIKE", "Dislike"),
                            ("COMENTARIO", "Comentario"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentarios", models.TextField(blank=True, null=True)),
                (
                    "bitacor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.bitacors"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interacciones",
            },
        ),
    ]
