# Generated by Django 4.2.4 on 2023-11-25 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0022_interaccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bitacors",
            name="nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="coment_pro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "productos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.producto_pm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coment_pro",
            },
        ),
    ]
