# Generated by Django 4.2.4 on 2023-11-27 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_datos_envio_mesaño_datos_envio_segu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrito",
            name="productos",
        ),
    ]
