# Generated by Django 4.2.4 on 2023-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_remove_datos_envio_correo_alter_datos_envio_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos_envio",
            name="barrio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datos_envio",
            name="email",
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
