# Generated by Django 4.2.4 on 2023-12-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_totales"),
    ]

    operations = [
        migrations.AddField(
            model_name="datos_envio",
            name="cedula",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
