# Generated by Django 4.2.4 on 2023-12-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_datos_envio_guardado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datos_envio",
            name="guardado",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
